---
- name: Clone
  hosts: reddit-app
  tasks:
    - name: Clone repo
      git:
        repo: https://github.com/express42/reddit.git
        dest: /home/mikh_androsov/reddit
      tags:
        - skip_ansible_lint
